// Code generated by reactGen. DO NOT EDIT.

package app

import "myitcv.io/react"

func (t *TabDef) ShouldComponentUpdateIntf(nextProps, prevState, nextState interface{}) bool {
	res := false

	{
		res = t.Props() != nextProps.(TabProps) || res
	}
	return res
}

// Props is an auto-generated proxy to the current props of Tab
func (t *TabDef) Props() TabProps {
	uprops := t.ComponentDef.Props()
	return uprops.(TabProps)
}

func (t TabProps) EqualsIntf(val interface{}) bool {
	return t == val.(TabProps)
}

var _ react.Equals = TabProps{}
